[[annotation]]
file="example/exac.vcf"
# the special name 'ID' pulls out the rs id from the VCF
fields = ["AC_AFR", "AC_AMR", "AC_EAS", "ID"]
ops=["first", "first", "first", "first"]

[[annotation]]
# count is for alignments that are mapped (-F4) with mapq > 0
file="example/ex.bam"
names=["map", "coverage"] # map, coverage, and seq are special values for bam annotations
fields=["mapq", "coverage"]
ops=["mean", "count"]


[[annotation]]
file="example/fitcons.bed"
names=["otto_start", "otto_end", "otto_len", "otto_sum", "otto_mean", "otto_loc"]
columns=[4, 4, 4, 4, 4, 4]
# when a custom value is needed, specify arbitrary javascript after "js:"
# the variable available will be:
# + vals: the list of values from this annotation
# + chrom: the chrom of the variant being annotated
# + start: the (0-based) start of the variant being annotated
# + end: the end of the variant being annotated
# the result of the expression can be anything. it will be converted to a string.
# loc() and mean() are defined in examples/custom.js
ops=["js:start", "js:end", "js:vals.length", "js:sum=0;for(i=0;i<vals.length;i++){sum+=vals[i]};vals", "js:mean(vals)", "js:loc(chrom, start, end)"]
# note the last 2 use functions declared in js above.

# it is also possible to define some javascript functions that will be
# available. This is specified as a .js file to the vcfanno executable as
# ./vcfanno -js some.js ... see example/custom.js for an example.


# To annotated with cadd phred scores, include this section, but instead use the full-genome encoded
# cadd scores from 
# https://s3.amazonaws.com/vcfanno/cadd_v1.2.idx
# https://s3.amazonaws.com/vcfanno/cadd_v1.2.bin
# See: https://github.com/brentp/vcfanno/blob/master/caddencode/README.md
[caddidx]
file="example/cadd.sub.idx"
names=["cadd_phred_score", "cadd_max"]
ops=["concat", "max"]
