[[annotation]]
file="example/exac.vcf"
fields = ["AC_AFR", "AC_AMR", "AC_EAS"]
ops=["first", "first", "first"]

[[annotation]]
file="example/fitcons.bed"
columns = [4]
names=["fitcons_mean"]
ops=["mean"]

[[annotation]]
#count is currently the only valid option for a bam
#current method is to count alignments that are mapped (-F4) with mapq > 0
file="example/ex.bam"
names=["ex_bam_depth"]

[[annotation]]
file="example/fitcons.bed"
names=["otto"]
columns=[4]
# when a custom value is needed, specify arbitrary javascript after "js:"
# the variable available will be:
# + vals: the list of values from this annotation
# + chrom: the chrom of the variant being annotated
# + start: the (0-based) start of the variant being annotated
# + end: the end of the variant being annotated
# the result of the expression can be anything. it will be converted to a string.
ops=["js:vals.length"]
