language: go

go:
  - 1.3
  - 1.4
  - 1.4.1
  - 1.4.2
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get vbom.ml/util/sortorder
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci

